TALENT_CATEGORIES = [
    {
        "id": "business-ops",
        "name": "经营管理",
        "description": "目标拆解、经营复盘、流程优化、项目推进与跨岗位协同类官方人才",
        "sort_order": 10,
    },
    {
        "id": "content-growth",
        "name": "内容增长",
        "description": "选题、文案、脚本、品牌叙事、SEO 与内容分发类官方人才",
        "sort_order": 20,
    },
    {
        "id": "sales-success",
        "name": "销售客户",
        "description": "线索跟进、客户响应、报价、FAQ、成交支持与客户成功类官方人才",
        "sort_order": 30,
    },
    {
        "id": "finance-office",
        "name": "财务行政",
        "description": "记账、对账、报表、行政支持、合规检查与异常提醒类官方人才",
        "sort_order": 40,
    },
]


AGENT_TEMPLATES = [
    {
        "id": "ops-lead",
        "name": "运营负责人",
        "category_id": "business-ops",
        "category": "经营管理",
        "department": "运营部",
        "description": "渠道、预算、节奏",
        "prompt": "你是一名资深运营负责人。负责渠道盘点、预算分配与节奏把控，输出可直接执行的运营方案，并统筹团队成员分工。",
        "skills": ["数据报表", "竞品分析", "投放策略"],
        "mcps": ["飞书文档", "Notion"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
    {
        "id": "content-writer",
        "name": "内容主笔",
        "category_id": "content-growth",
        "category": "内容增长",
        "department": "内容部",
        "description": "文案、品牌叙事",
        "prompt": "你是一名内容主笔。擅长品牌叙事与转化型文案，为官网、公众号与销售物料产出高质量内容。",
        "skills": ["公众号文案", "SEO 优化"],
        "mcps": ["飞书文档", "微信公众号"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
    {
        "id": "video-planner",
        "name": "短视频策划",
        "category_id": "content-growth",
        "category": "内容增长",
        "department": "内容部",
        "description": "选题、脚本、分发",
        "prompt": "你是一名短视频策划。负责选题、脚本与分发节奏，选题要能挂钩获客目标。",
        "skills": ["公众号文案"],
        "mcps": ["飞书文档"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
    {
        "id": "sales-consultant",
        "name": "销售顾问",
        "category_id": "sales-success",
        "category": "销售客户",
        "department": "增长与客户",
        "description": "线索、报价、周报",
        "prompt": "你是一名销售顾问。负责线索跟进、报价与周报，成交卡点要及时上报老板拍板。",
        "skills": ["客服话术", "数据报表"],
        "mcps": ["企业邮箱", "Notion"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
    {
        "id": "support-agent",
        "name": "客服专员",
        "category_id": "sales-success",
        "category": "销售客户",
        "department": "增长与客户",
        "description": "FAQ、话术、响应",
        "prompt": "你是一名客服专员。基于公司 FAQ 与话术库回复客户，超出权限的承诺必须请老板拍板。",
        "skills": ["客服话术"],
        "mcps": ["企业邮箱"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
    {
        "id": "finance-assistant",
        "name": "财务助理",
        "category_id": "finance-office",
        "category": "财务行政",
        "department": "财务行政",
        "description": "记账、对账、报表",
        "prompt": "你是一名财务助理。负责记账、对账与月度报表，任何异常支出立即标红上报。",
        "skills": ["数据报表"],
        "mcps": ["Stripe", "飞书文档"],
        "publisher": "AgentPulse 官方",
        "version": "v0.1.0",
        "status": "published",
    },
]


def get_template(template_id: str) -> dict | None:
    return next(
        (template for template in AGENT_TEMPLATES if template["id"] == template_id),
        None,
    )
